// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertAmountToCents(arg1:number):Promise<number>;

export function ConvertCentsToAmount(arg1:number):Promise<number>;

export function CreatePaymentIntent(arg1:main.StripePaymentIntentRequest):Promise<main.StripePaymentIntentResponse>;

export function GetBalance(arg1:string):Promise<main.BalanceResponse>;

export function GetDatabaseStatus():Promise<Record<string, any>>;

export function GetStripePublishableKey():Promise<string>;

export function GetUserByLogin(arg1:string):Promise<main.User>;

export function GetUserMeta(arg1:string):Promise<main.UserMetaResponse>;

export function GetUserTransactions(arg1:string,arg2:number):Promise<main.TransactionListResponse>;

export function Register(arg1:main.RegisterRequest):Promise<main.User>;

export function UpdateBalance(arg1:main.BalanceRequest):Promise<void>;

export function ValidateUserSession(arg1:string):Promise<boolean>;
