// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertAmountToCents(arg1) {
  return window['go']['main']['App']['ConvertAmountToCents'](arg1);
}

export function ConvertCentsToAmount(arg1) {
  return window['go']['main']['App']['ConvertCentsToAmount'](arg1);
}

export function CreatePaymentIntent(arg1) {
  return window['go']['main']['App']['CreatePaymentIntent'](arg1);
}

export function GetBalance(arg1) {
  return window['go']['main']['App']['GetBalance'](arg1);
}

export function GetDatabaseStatus() {
  return window['go']['main']['App']['GetDatabaseStatus']();
}

export function GetStripePublishableKey() {
  return window['go']['main']['App']['GetStripePublishableKey']();
}

export function GetUserByLogin(arg1) {
  return window['go']['main']['App']['GetUserByLogin'](arg1);
}

export function GetUserMeta(arg1) {
  return window['go']['main']['App']['GetUserMeta'](arg1);
}

export function GetUserTransactions(arg1, arg2) {
  return window['go']['main']['App']['GetUserTransactions'](arg1, arg2);
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function UpdateBalance(arg1) {
  return window['go']['main']['App']['UpdateBalance'](arg1);
}

export function ValidateUserSession(arg1) {
  return window['go']['main']['App']['ValidateUserSession'](arg1);
}
